server:
  context-path: /uaa
  port: 5000

management:
  security:
    enabled: false
  context-path: /mgmt

eureka:
  instance:
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}

spring:
  datasource:
    url: com.mysql.jdbc.Driver
    driver-class-name: jdbc:mysql://127.0.0.1:3306/spring-boot-cloud?characterEncoding=UTF-8
    username: root
    password: root
