spring:
  application:
    name: zipkin
  rabbitmq:
    host: 203.195.213.43
    port: 5672
    username: guest
    password: guest

server:
  port: 9411

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}
